// Initial mock data
const mockAgents = [
  {
    id: '1',
    name: 'Customer Support Assistant',
    description: 'Handles customer inquiries, resolves issues, and provides product information',
    type: 'conversational',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1625314887424-9f190599bd56?w=400',
    capabilities: ['Customer Service', 'Product Knowledge', 'Ticket Management', 'Email Support'],
    metrics: {
      totalInteractions: 15234,
      successRate: 94,
      avgResponseTime: 450,
      uptime: 99.8,
    },
    configuration: {
      temperature: 0.7,
      maxTokens: 2048,
      model: 'GPT-4',
      systemPrompt: 'You are a helpful customer support assistant. Be empathetic, professional, and solution-focused.',
    },
    createdAt: 'October 1, 2025',
    lastActive: '2 minutes ago',
  },
  {
    id: '2',
    name: 'Data Analyst Pro',
    description: 'Analyzes datasets, generates insights, and creates visualizations',
    type: 'analytical',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    capabilities: ['Data Analysis', 'Visualization', 'Statistical Modeling', 'Report Generation'],
    metrics: {
      totalInteractions: 8456,
      successRate: 97,
      avgResponseTime: 890,
      uptime: 98.5,
    },
    configuration: {
      temperature: 0.3,
      maxTokens: 3000,
      model: 'GPT-4',
      systemPrompt: 'You are an expert data analyst. Provide clear, data-driven insights with statistical rigor.',
    },
    createdAt: 'September 15, 2025',
    lastActive: '15 minutes ago',
  },
  {
    id: '3',
    name: 'Content Creator',
    description: 'Generates creative content, marketing copy, and social media posts',
    type: 'creative',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=400',
    capabilities: ['Content Writing', 'Copywriting', 'Social Media', 'SEO Optimization'],
    metrics: {
      totalInteractions: 6789,
      successRate: 92,
      avgResponseTime: 620,
      uptime: 99.2,
    },
    configuration: {
      temperature: 0.9,
      maxTokens: 2500,
      model: 'GPT-4',
      systemPrompt: 'You are a creative content writer. Generate engaging, original content that resonates with audiences.',
    },
    createdAt: 'September 20, 2025',
    lastActive: '1 hour ago',
  },
  {
    id: '4',
    name: 'Workflow Automator',
    description: 'Automates repetitive tasks and manages workflow processes',
    type: 'automation',
    status: 'paused',
    capabilities: ['Task Automation', 'Workflow Management', 'Integration', 'Scheduling'],
    metrics: {
      totalInteractions: 12034,
      successRate: 89,
      avgResponseTime: 350,
      uptime: 97.3,
    },
    configuration: {
      temperature: 0.5,
      maxTokens: 1500,
      model: 'GPT-3.5',
      systemPrompt: 'You are an automation specialist. Execute tasks efficiently and handle errors gracefully.',
    },
    createdAt: 'August 30, 2025',
    lastActive: '3 hours ago',
  },
  {
    id: '5',
    name: 'Code Assistant',
    description: 'Helps with code review, debugging, and technical documentation',
    type: 'analytical',
    status: 'training',
    capabilities: ['Code Review', 'Debugging', 'Documentation', 'Best Practices'],
    metrics: {
      totalInteractions: 4567,
      successRate: 95,
      avgResponseTime: 720,
      uptime: 96.8,
    },
    configuration: {
      temperature: 0.4,
      maxTokens: 4000,
      model: 'Claude-3',
      systemPrompt: 'You are an expert software engineer. Provide clear, accurate technical guidance.',
    },
    createdAt: 'October 10, 2025',
    lastActive: '30 minutes ago',
  },
  {
    id: '6',
    name: 'Research Assistant',
    description: 'Conducts research, summarizes information, and answers complex queries',
    type: 'conversational',
    status: 'active',
    capabilities: ['Research', 'Summarization', 'Fact-Checking', 'Citation'],
    metrics: {
      totalInteractions: 9234,
      successRate: 96,
      avgResponseTime: 680,
      uptime: 99.5,
    },
    configuration: {
      temperature: 0.6,
      maxTokens: 3500,
      model: 'GPT-4',
      systemPrompt: 'You are a research assistant. Provide well-researched, accurate information with proper citations.',
    },
    createdAt: 'September 5, 2025',
    lastActive: '5 minutes ago',
  },
];